[build]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
runner = "/opt/riscv/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /opt/riscv/sysroot/lib"
linker = "riscv64-unknown-linux-gnu-gcc"
